version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type/typescript"
      - "type/deps"
      - "status/investigating"
    groups:
      non-major-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type/docker"
      - "type/deps"
      - "status/investigating"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type/actions"
      - "type/ci"
      - "type/deps"
      - "status/investigating"

