name: Build and push Docker image to container registry
on:
    push:
        branches:
            - '**'
        tags:
            - 'v*.*.*'

jobs:
    skip_duplicate_jobs:
        name: Skip duplicate jobs
        continue-on-error: true
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5
              with:
                  paths_ignore: '["**/README.md", "**/docs/**", "**/.gitignore", "**/LICENSE"]'
                  concurrent_skipping: same_content_newer

    build_and_push_api_app_docker_image_to_container_registry:
        name: Build and push Docker image to container registry
        runs-on: ubuntu-latest
        needs: skip_duplicate_jobs
        if: needs.skip_duplicate_jobs.outputs.should_skip != 'true'

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}
                  labels: |
                      org.opencontainers.image.title=Loqui API
                      org.opencontainers.image.description=See the [repository](https://github.com/The-Loqui-Project/Loqui/tree/main/apps/api).
                      org.opencontainers.image.vendor=The Loqui Project
                  tags: |
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: |
                    pnpm
                  key: ${{ runner.os }}-api-node-${{ hashFiles('apps/api/package-lock.json') }}
                  restore-keys: |
                    ${{ runner.os }}-api-node-

            - name: Inject cache into Docker
              uses: reproducible-containers/buildkit-cache-dance@v3.1.0
              with:
                  cache-map: |
                      {
                      "pnpm": "/pnpm"
                      }
                  skip-extraction: ${{ steps.cache.outputs.cache-hit }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/api/
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

    build_and_push_web_app_docker_image_to_container_registry:
        name: Build and push Docker image to container registry
        runs-on: ubuntu-latest
        needs: skip_duplicate_jobs
        if: needs.skip_duplicate_jobs.outputs.should_skip != 'true'

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}
                  labels: |
                      org.opencontainers.image.title=Loqui web application
                      org.opencontainers.image.description=See the [repository](https://github.com/The-Loqui-Project/Loqui/tree/main/apps/web).
                      org.opencontainers.image.vendor=The Loqui Project
                  tags: |
                      type=schedule
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
                      type=sha
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Checkout
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v3
              id: cache
              with:
                  path: |
                    pnpm
                  key: ${{ runner.os }}-web-node-${{ hashFiles('apps/web/package-lock.json') }}
                  restore-keys: |
                    ${{ runner.os }}-web-node-

            - name: Inject cache into Docker
              uses: reproducible-containers/buildkit-cache-dance@v3.1.0
              with:
                  cache-map: |
                      {
                      "pnpm": "/pnpm"
                      }
                  skip-extraction: ${{ steps.cache.outputs.cache-hit }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/web/
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
