name: Build Web

on:
  push:
    branches:
      - '**'
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/build_web.yml'
  pull_request:
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/build_web.yml'
  workflow_dispatch:

jobs:
  check_changes:
    name: Check for Web changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.filter.outputs.web }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
              - 'packages/**'
              - 'pnpm-lock.yaml'

  skip_duplicate_jobs:
    name: Skip duplicate jobs
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.has_changes == 'true'
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md", "**/docs/**", "**/.gitignore", "**/LICENSE"]'
          concurrent_skipping: never
          skip_after_successful_duplicate: false

  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: [check_changes, skip_duplicate_jobs]
    if: needs.check_changes.outputs.has_changes == 'true' && needs.skip_duplicate_jobs.outputs.should_skip != 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Update meta.ts with branch and commit
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            BRANCH="${GITHUB_REF#refs/tags/}"
          fi
          COMMIT=$(git rev-parse --short HEAD)
          sed -i "s|export const branch: null \| string = null|export const branch: null \| string = '${BRANCH}'|" packages/meta/meta.ts
          sed -i "s|export const commit: null \| string = null|export const commit: null \| string = '${COMMIT}'|" packages/meta/meta.ts
      
      - name: Determine URL variables based on branch
        id: set-urls
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            BRANCH="${GITHUB_REF#refs/tags/}"
          fi
          
          if [[ "$BRANCH" == "prod" ]]; then
            echo "CURRENT_URL=${{ vars.PROD_CURRENT_URL }}" >> $GITHUB_OUTPUT
            echo "API_URL=${{ vars.PROD_API_URL }}" >> $GITHUB_OUTPUT
            echo "Using production URLs for branch: $BRANCH"
          else
            echo "CURRENT_URL=${{ vars.STAGING_CURRENT_URL }}" >> $GITHUB_OUTPUT
            echo "API_URL=${{ vars.STAGING_API_URL }}" >> $GITHUB_OUTPUT
            echo "Using staging URLs for branch: $BRANCH"
          fi

      - name: Build Web
        run: |
          cd apps/web
          CURRENT_URL="${{ steps.set-urls.outputs.CURRENT_URL }}" API_URL="${{ steps.set-urls.outputs.API_URL }}" pnpm run build

  auto_success:
    name: Auto Success (No Web Changes)
    runs-on: ubuntu-latest
    needs: check_changes
    if: needs.check_changes.outputs.has_changes != 'true'
    steps:
      - name: No Web changes detected
        run: echo "No Web app changes detected - workflow marked as successful"